<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="45" total="46" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Automation" duration-ms="3037" started-at="2018-03-12T08:50:41Z" finished-at="2018-03-12T08:50:44Z">
    <groups>
    </groups>
    <test name="Test ALL Possible Logins" duration-ms="1350" started-at="2018-03-12T08:50:41Z" finished-at="2018-03-12T08:50:43Z">
      <class name="com.dw.api.automation.TestScripts.LoginTest">
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="initateExtentManager" is-config="true" duration-ms="576" started-at="2018-03-12T14:20:41Z" finished-at="2018-03-12T14:20:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="FAIL" signature="loginAsPM()[pri:1, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="loginAsPM" duration-ms="66" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.LoginTest.loginAsPM(LoginTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPM -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="afterMethod" is-config="true" duration-ms="4" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPM status=FAILURE method=LoginTest.loginAsPM()[pri:1, instance:com.dw.api.automation.TestScripts.LoginTest@724af044] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="loginAsBAM()[pri:2, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="loginAsBAM" duration-ms="34" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.LoginTest.loginAsBAM(LoginTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBAM -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsBAM status=FAILURE method=LoginTest.loginAsBAM()[pri:2, instance:com.dw.api.automation.TestScripts.LoginTest@724af044] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="loginAsCA()[pri:2, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="loginAsCA" duration-ms="27" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.LoginTest.loginAsCA(LoginTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsCA -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsCA status=FAILURE method=LoginTest.loginAsCA()[pri:2, instance:com.dw.api.automation.TestScripts.LoginTest@724af044] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.LoginTest@724af044]" name="tear" is-config="true" duration-ms="617" started-at="2018-03-12T14:20:42Z" finished-at="2018-03-12T14:20:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.LoginTest -->
    </test> <!-- Test ALL Possible Logins -->
    <test name="AddcNew Partner Org Test" duration-ms="582" started-at="2018-03-12T08:50:43Z" finished-at="2018-03-12T08:50:43Z">
      <class name="com.dw.api.automation.TestScripts.AddNewPartnerOrgTest">
        <test-method status="FAIL" signature="loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="loginAsPm" duration-ms="6" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.AddNewPartnerOrgTest.loginAsPm(AddNewPartnerOrgTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPm -->
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="initateExtentManager" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="18" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPm status=FAILURE method=AddNewPartnerOrgTest.loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="verifyMpnId" duration-ms="378" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.verifyMPN(OrganisationPF.java:44)
	at com.dw.api.automation.TestScripts.AddNewPartnerOrgTest.verifyMpnId(AddNewPartnerOrgTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMpnId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyMpnId status=FAILURE method=AddNewPartnerOrgTest.verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addNewPartnerOrganisation()[pri:3, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="addNewPartnerOrganisation" duration-ms="31" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.addNewPartnerOrganisation(OrganisationPF.java:59)
	at com.dw.api.automation.TestScripts.AddNewPartnerOrgTest.addNewPartnerOrganisation(AddNewPartnerOrgTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewPartnerOrganisation -->
        <test-method status="FAIL" signature="approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="approveNewOrgByBAM" duration-ms="29" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByBam(OrganisationPF.java:155)
	at com.dw.api.automation.TestScripts.AddNewPartnerOrgTest.approveNewOrgByBAM(AddNewPartnerOrgTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByBAM -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewPartnerOrganisation status=FAILURE method=AddNewPartnerOrgTest.addNewPartnerOrganisation()[pri:3, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="3" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByBAM status=FAILURE method=AddNewPartnerOrgTest.approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewOrgByCA()[pri:5, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="approveNewOrgByCA" duration-ms="3" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsCA(ApiLoginPF.java:150)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByCA(OrganisationPF.java:207)
	at com.dw.api.automation.TestScripts.AddNewPartnerOrgTest.approveNewOrgByCA(AddNewPartnerOrgTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByCA -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByCA status=FAILURE method=AddNewPartnerOrgTest.approveNewOrgByCA()[pri:5, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.AddNewPartnerOrgTest@77caeb3e]" name="tear" is-config="true" duration-ms="104" started-at="2018-03-12T14:20:43Z" finished-at="2018-03-12T14:20:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.AddNewPartnerOrgTest -->
    </test> <!-- AddcNew Partner Org Test -->
    <test name="Customer On Boarding " duration-ms="155" started-at="2018-03-12T08:50:44Z" finished-at="2018-03-12T08:50:44Z">
      <class name="com.dw.api.automation.TestScripts.CustomerOnBoardingTest">
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="initateExtentManager" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="FAIL" signature="loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="loginAsPm" duration-ms="2" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.loginAsPm(CustomerOnBoardingTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPm -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPm status=FAILURE method=CustomerOnBoardingTest.loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="verifyMpnId" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.verifyMPN(OrganisationPF.java:44)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.verifyMpnId(CustomerOnBoardingTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMpnId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyMpnId status=FAILURE method=CustomerOnBoardingTest.verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addNewPartnerOrganisation()[pri:3, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="addNewPartnerOrganisation" duration-ms="4" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.addNewPartnerOrganisation(OrganisationPF.java:59)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.addNewPartnerOrganisation(CustomerOnBoardingTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewPartnerOrganisation -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewPartnerOrganisation status=FAILURE method=CustomerOnBoardingTest.addNewPartnerOrganisation()[pri:3, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="approveNewOrgByBAM" duration-ms="14" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByBam(OrganisationPF.java:155)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.approveNewOrgByBAM(CustomerOnBoardingTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByBAM -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByBAM status=FAILURE method=CustomerOnBoardingTest.approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewOrgByCA()[pri:5, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="approveNewOrgByCA" duration-ms="13" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsCA(ApiLoginPF.java:150)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByCA(OrganisationPF.java:207)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.approveNewOrgByCA(CustomerOnBoardingTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByCA -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="2" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByCA status=FAILURE method=CustomerOnBoardingTest.approveNewOrgByCA()[pri:5, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="createNewCustomer()[pri:6, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="createNewCustomer" duration-ms="13" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.CustomerPF.createNewCustomer(CustomerPF.java:36)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.createNewCustomer(CustomerOnBoardingTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewCustomer -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createNewCustomer status=FAILURE method=CustomerOnBoardingTest.createNewCustomer()[pri:6, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="getCustomerId()[pri:7, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="getCustomerId" duration-ms="5" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CustomerPF.getCustomerId(CustomerPF.java:98)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.getCustomerId(CustomerOnBoardingTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCustomerId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCustomerId status=FAILURE method=CustomerOnBoardingTest.getCustomerId()[pri:7, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewCustomerFromBam()[pri:8, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="approveNewCustomerFromBam" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CustomerPF.approveNewCustomerFromBam(CustomerPF.java:133)
	at com.dw.api.automation.TestScripts.CustomerOnBoardingTest.approveNewCustomerFromBam(CustomerOnBoardingTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewCustomerFromBam -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewCustomerFromBam status=FAILURE method=CustomerOnBoardingTest.approveNewCustomerFromBam()[pri:8, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.CustomerOnBoardingTest@91161c7]" name="tear" is-config="true" duration-ms="82" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.CustomerOnBoardingTest -->
    </test> <!-- Customer On Boarding  -->
    <test name="Market Place And Contract Management" duration-ms="98" started-at="2018-03-12T08:50:44Z" finished-at="2018-03-12T08:50:44Z">
      <class name="com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest">
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="initateExtentManager" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="FAIL" signature="loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="loginAsPm" duration-ms="5" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest.loginAsPm(MarketPlaceAndContractManagementTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPm -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="afterMethod" is-config="true" duration-ms="2" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPm status=FAILURE method=MarketPlaceAndContractManagementTest.loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addBaseProductWithTwoLicenses()[pri:2, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="addBaseProductWithTwoLicenses" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.MarketPlaceAndContractManagementPF.addBaseProductWithTwoLicenses(MarketPlaceAndContractManagementPF.java:26)
	at com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest.addBaseProductWithTwoLicenses(MarketPlaceAndContractManagementTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addBaseProductWithTwoLicenses -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addBaseProductWithTwoLicenses status=FAILURE method=MarketPlaceAndContractManagementTest.addBaseProductWithTwoLicenses()[pri:2, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addAddOnProductWithOneLicenses()[pri:3, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="addAddOnProductWithOneLicenses" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.MarketPlaceAndContractManagementPF.addAddOnwithOneLicenses(MarketPlaceAndContractManagementPF.java:57)
	at com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest.addAddOnProductWithOneLicenses(MarketPlaceAndContractManagementTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddOnProductWithOneLicenses -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addAddOnProductWithOneLicenses status=FAILURE method=MarketPlaceAndContractManagementTest.addAddOnProductWithOneLicenses()[pri:3, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="placeOrder()[pri:4, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="placeOrder" duration-ms="12" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.MarketPlaceAndContractManagementPF.placeOrder(MarketPlaceAndContractManagementPF.java:98)
	at com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest.placeOrder(MarketPlaceAndContractManagementTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=placeOrder status=FAILURE method=MarketPlaceAndContractManagementTest.placeOrder()[pri:4, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest@6093dd95]" name="tear" is-config="true" duration-ms="66" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.MarketPlaceAndContractManagementTest -->
    </test> <!-- Market Place And Contract Management -->
    <test name="Order Provision" duration-ms="120" started-at="2018-03-12T08:50:44Z" finished-at="2018-03-12T08:50:44Z">
      <class name="com.dw.api.automation.TestScripts.OrderProvisonTest">
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="initateExtentManager" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="FAIL" signature="loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="loginAsPm" duration-ms="7" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.OrderProvisonTest.loginAsPm(OrderProvisonTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPm -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPm status=FAILURE method=OrderProvisonTest.loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="orderProvisionForBaseProduct()[pri:2, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="orderProvisionForBaseProduct" duration-ms="4" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrderProvisonPF.orderProvisionForBaseProduct(OrderProvisonPF.java:30)
	at com.dw.api.automation.TestScripts.OrderProvisonTest.orderProvisionForBaseProduct(OrderProvisonTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderProvisionForBaseProduct -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=orderProvisionForBaseProduct status=FAILURE method=OrderProvisonTest.orderProvisionForBaseProduct()[pri:2, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="orderProvisionForAddOnProduct()[pri:3, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="orderProvisionForAddOnProduct" duration-ms="8" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrderProvisonPF.orderProvsionForAddOnProduct(OrderProvisonPF.java:79)
	at com.dw.api.automation.TestScripts.OrderProvisonTest.orderProvisionForAddOnProduct(OrderProvisonTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderProvisionForAddOnProduct -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=orderProvisionForAddOnProduct status=FAILURE method=OrderProvisonTest.orderProvisionForAddOnProduct()[pri:3, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.OrderProvisonTest@57baeedf]" name="tear" is-config="true" duration-ms="97" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.OrderProvisonTest -->
    </test> <!-- Order Provision -->
    <test name="Place Order With Coupan Code" duration-ms="220" started-at="2018-03-12T08:50:44Z" finished-at="2018-03-12T08:50:44Z">
      <class name="com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest">
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="initateExtentManager" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="FAIL" signature="loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="loginAsPm" duration-ms="2" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.loginAsPm(PlaceOrderWithCoupanCodeTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPm -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPm status=FAILURE method=PlaceOrderWithCoupanCodeTest.loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="verifyMpnId" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.verifyMPN(OrganisationPF.java:44)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.verifyMpnId(PlaceOrderWithCoupanCodeTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMpnId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyMpnId status=FAILURE method=PlaceOrderWithCoupanCodeTest.verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addNewPartnerOrganisation()[pri:3, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="addNewPartnerOrganisation" duration-ms="10" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.addNewPartnerOrganisation(OrganisationPF.java:59)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.addNewPartnerOrganisation(PlaceOrderWithCoupanCodeTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewPartnerOrganisation -->
        <test-method status="FAIL" signature="approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="approveNewOrgByBAM" duration-ms="6" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByBam(OrganisationPF.java:155)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.approveNewOrgByBAM(PlaceOrderWithCoupanCodeTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByBAM -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewPartnerOrganisation status=FAILURE method=PlaceOrderWithCoupanCodeTest.addNewPartnerOrganisation()[pri:3, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByBAM status=FAILURE method=PlaceOrderWithCoupanCodeTest.approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewOrgByCA()[pri:5, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="approveNewOrgByCA" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsCA(ApiLoginPF.java:150)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByCA(OrganisationPF.java:207)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.approveNewOrgByCA(PlaceOrderWithCoupanCodeTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByCA -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByCA status=FAILURE method=PlaceOrderWithCoupanCodeTest.approveNewOrgByCA()[pri:5, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="createNewCustomer()[pri:6, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="createNewCustomer" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.CustomerPF.createNewCustomer(CustomerPF.java:36)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.createNewCustomer(PlaceOrderWithCoupanCodeTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewCustomer -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createNewCustomer status=FAILURE method=PlaceOrderWithCoupanCodeTest.createNewCustomer()[pri:6, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="getCustomerId()[pri:7, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="getCustomerId" duration-ms="2" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CustomerPF.getCustomerId(CustomerPF.java:98)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.getCustomerId(PlaceOrderWithCoupanCodeTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCustomerId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCustomerId status=FAILURE method=PlaceOrderWithCoupanCodeTest.getCustomerId()[pri:7, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewCustomerFromBam()[pri:8, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="approveNewCustomerFromBam" duration-ms="25" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CustomerPF.approveNewCustomerFromBam(CustomerPF.java:133)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.approveNewCustomerFromBam(PlaceOrderWithCoupanCodeTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewCustomerFromBam -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewCustomerFromBam status=FAILURE method=PlaceOrderWithCoupanCodeTest.approveNewCustomerFromBam()[pri:8, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="createCoupan()[pri:9, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="createCoupan" duration-ms="4" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CoupanPF.createCoupanForBaseProduct(CoupanPF.java:36)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.createCoupan(PlaceOrderWithCoupanCodeTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCoupan -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createCoupan status=FAILURE method=PlaceOrderWithCoupanCodeTest.createCoupan()[pri:9, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="getCouponCode()[pri:10, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="getCouponCode" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.CoupanPF.getCouponCode(CoupanPF.java:144)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.getCouponCode(PlaceOrderWithCoupanCodeTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCouponCode -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCouponCode status=FAILURE method=PlaceOrderWithCoupanCodeTest.getCouponCode()[pri:10, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addBaseProductWithTwoLicenses()[pri:11, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="addBaseProductWithTwoLicenses" duration-ms="7" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.MarketPlaceAndContractManagementPF.addBaseProductWithTwoLicenses(MarketPlaceAndContractManagementPF.java:26)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.addBaseProductWithTwoLicenses(PlaceOrderWithCoupanCodeTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addBaseProductWithTwoLicenses -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addBaseProductWithTwoLicenses status=FAILURE method=PlaceOrderWithCoupanCodeTest.addBaseProductWithTwoLicenses()[pri:11, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addAddOnProductWithOneLicenses()[pri:12, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="addAddOnProductWithOneLicenses" duration-ms="29" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.MarketPlaceAndContractManagementPF.addAddOnwithOneLicenses(MarketPlaceAndContractManagementPF.java:57)
	at com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest.addAddOnProductWithOneLicenses(PlaceOrderWithCoupanCodeTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddOnProductWithOneLicenses -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="afterMethod" is-config="true" duration-ms="8" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addAddOnProductWithOneLicenses status=FAILURE method=PlaceOrderWithCoupanCodeTest.addAddOnProductWithOneLicenses()[pri:12, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest@77cd7a0]" name="tear" is-config="true" duration-ms="99" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.PlaceOrderWithCoupanCodeTest -->
    </test> <!-- Place Order With Coupan Code -->
    <test name="Place Order With Vat  Coupan Code" duration-ms="214" started-at="2018-03-12T08:50:44Z" finished-at="2018-03-12T08:50:44Z">
      <class name="com.dw.api.automation.TestScripts.PlaceOrderWithVatTest">
        <test-method status="PASS" signature="initateExtentManager()[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="initateExtentManager" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initateExtentManager -->
        <test-method status="FAIL" signature="loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="loginAsPm" duration-ms="15" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.loginAsPm(PlaceOrderWithVatTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsPm -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginAsPm status=FAILURE method=PlaceOrderWithVatTest.loginAsPm()[pri:1, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="verifyMpnId" duration-ms="30" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.verifyMPN(OrganisationPF.java:44)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.verifyMpnId(PlaceOrderWithVatTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMpnId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyMpnId status=FAILURE method=PlaceOrderWithVatTest.verifyMpnId()[pri:2, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="addNewPartnerOrganisationWithVat()[pri:3, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="addNewPartnerOrganisationWithVat" duration-ms="5" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.OrganisationPF.addNewPartnerOrganisationWithVat(OrganisationPF.java:249)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.addNewPartnerOrganisationWithVat(PlaceOrderWithVatTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewPartnerOrganisationWithVat -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewPartnerOrganisationWithVat status=FAILURE method=PlaceOrderWithVatTest.addNewPartnerOrganisationWithVat()[pri:3, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="approveNewOrgByBAM" duration-ms="4" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByBam(OrganisationPF.java:155)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.approveNewOrgByBAM(PlaceOrderWithVatTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrgByBAM -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrgByBAM status=FAILURE method=PlaceOrderWithVatTest.approveNewOrgByBAM()[pri:4, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewOrganisationByCAwithVAT()[pri:5, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="approveNewOrganisationByCAwithVAT" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsCA(ApiLoginPF.java:150)
	at com.dw.api.automation.pagefactory.OrganisationPF.approveNewOrganisationByCAwithVAT(OrganisationPF.java:343)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.approveNewOrganisationByCAwithVAT(PlaceOrderWithVatTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewOrganisationByCAwithVAT -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewOrganisationByCAwithVAT status=FAILURE method=PlaceOrderWithVatTest.approveNewOrganisationByCAwithVAT()[pri:5, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="createNewCustomer()[pri:6, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="createNewCustomer" duration-ms="4" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.CustomerPF.createNewCustomer(CustomerPF.java:36)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.createNewCustomer(PlaceOrderWithVatTest.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewCustomer -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createNewCustomer status=FAILURE method=PlaceOrderWithVatTest.createNewCustomer()[pri:6, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="getCustomerId()[pri:7, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="getCustomerId" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CustomerPF.getCustomerId(CustomerPF.java:98)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.getCustomerId(PlaceOrderWithVatTest.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCustomerId -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getCustomerId status=FAILURE method=PlaceOrderWithVatTest.getCustomerId()[pri:7, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="approveNewCustomerFromBam()[pri:8, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="approveNewCustomerFromBam" duration-ms="3" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CustomerPF.approveNewCustomerFromBam(CustomerPF.java:133)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.approveNewCustomerFromBam(PlaceOrderWithVatTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approveNewCustomerFromBam -->
        <test-method status="FAIL" signature="addBaseProductWithTwoLicenses()[pri:9, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="addBaseProductWithTwoLicenses" duration-ms="5" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsPM(ApiLoginPF.java:50)
	at com.dw.api.automation.pagefactory.MarketPlaceAndContractManagementPF.addBaseProductWithTwoLicenses(MarketPlaceAndContractManagementPF.java:26)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.addBaseProductWithTwoLicenses(PlaceOrderWithVatTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addBaseProductWithTwoLicenses -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=approveNewCustomerFromBam status=FAILURE method=PlaceOrderWithVatTest.approveNewCustomerFromBam()[pri:8, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addBaseProductWithTwoLicenses status=FAILURE method=PlaceOrderWithVatTest.addBaseProductWithTwoLicenses()[pri:9, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="placeOrder()[pri:10, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="placeOrder" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=placeOrder status=SUCCESS method=PlaceOrderWithVatTest.placeOrder()[pri:10, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="createCoupan()[pri:11, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="createCoupan" duration-ms="5" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.libs.FilloExcelUtility.readExcelWithTestName(FilloExcelUtility.java:109)
	at com.dw.api.automation.pagefactory.ApiLoginPF.loginAsBAM(ApiLoginPF.java:99)
	at com.dw.api.automation.pagefactory.CoupanPF.createCoupanForBaseProduct(CoupanPF.java:36)
	at com.dw.api.automation.TestScripts.PlaceOrderWithVatTest.createCoupan(PlaceOrderWithVatTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCoupan -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createCoupan status=FAILURE method=PlaceOrderWithVatTest.createCoupan()[pri:11, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="tear()[pri:0, instance:com.dw.api.automation.TestScripts.PlaceOrderWithVatTest@464bee09]" name="tear" is-config="true" duration-ms="119" started-at="2018-03-12T14:20:44Z" finished-at="2018-03-12T14:20:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.dw.api.automation.TestScripts.PlaceOrderWithVatTest -->
    </test> <!-- Place Order With Vat  Coupan Code -->
  </suite> <!-- Automation -->
</testng-results>
